## 브로드캐스팅(Broadcasting)
* 브로드캐스팅이란 Numpy 배열에서 차원의 크기가 서로 다른 배열에서도 산술 연산을 가능하게 하는 기능임
* 두 배열 간 차원의 크기가 (4, 2), (2, ) 일 때 산술 연산을 실행한다면 (2, )의 배열이 (4, 2) 행렬의 각 행에 대해 요소별 연산을 실행할 수 있음
* (2, )은 1차원 형태의 배열을 의미합니다. 즉, [a b]의 값을 지님

## 브로드캐스팅 허용 규칙
* 두 배열의 차원(ndim)이 같지 않다면 차원이 더 낮은 배열이 차원이 더 높은 배열과 같은 차원의 배열로 인식됨
* 반환된 배열은 연산을 수행한 배열 중 차원의 수(ndim)가 가장 큰 배열이 됨
* 연산에 사용된 배열과 반환된 배열의 차원의 크기(shape)가 같거나 1일 경우 브로드캐스팅이 가능함
* 브로드캐스팅이 적용된 배열의 차원 크기(shape)는 연산에 사용된 배열들의 차원의 크기에 대한 최소 공배수 값으로 사용함

## 브로드캐스팅(Broadcasting)
* 각 배열의 차원이 달라도 브로드캐스팅 허용 규칙에 위반되지 않는다면 연산이 가능함
* 형식 캐스팅(type casting)을 지원해 두 배열의 자료형(dtype)이 다르더라도 연산이 가능함
* 형식 캐스팅 : 자료형을 비교해 표현 범위가 더 넓은 자료형을 선택하는 것을 의미함

In [1]:
import numpy as np 

array1 = np.array([1, 2, 3, 4])._______(2, 2)
array2 = np.array([1.5, 2.5])
add = array1 + array2
print(add)

array1 = np.array([1, 2, 3, 4])
#array2 = np.array([1.5, 2.5])  # error
array2 = np.array([1.5])
add = array1 + array2
print('\n', add)

[[2.5 4.5]
 [4.5 6.5]]

 [2.5 3.5 4.5 5.5]


In [2]:
import numpy as np 

array1 = np.array([1, 2, 3, 4]).reshape(2, 2)
array2 = np.array([1.5, 2.5])
add = array1 + array2
print(add)

array1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
array2 = np.array([1.5, 2.5])
add = array1 + array2
print('\n', add)

[[2.5 4.5]
 [4.5 6.5]]

 [[ 2.5  4.5]
 [ 4.5  6.5]
 [ 6.5  8.5]
 [ 8.5 10.5]]


In [3]:
import numpy as np 

array1 = np.array([1, 2, 3, 4]).reshape(2, 2)
array2 = np.array([1.5, 2.5])
add = array1 + array2
print(add)

array1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
array2 = np.array([1.5])
add = array1 + array2
print('\n', add)

[[2.5 4.5]
 [4.5 6.5]]

 [[2.5 3.5]
 [4.5 5.5]
 [6.5 7.5]
 [8.5 9.5]]


In [4]:
import numpy as np 

x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(x.shape)  # Prints (2, 3)

col_means = ......
print(col_means)          # Prints [2. 3.5 5.]
print(col_means.shape)    # Prints (3,)
                          # Has a smaller rank than x!

mean_shifted = x - col_means
print('\n', mean_shifted)
print(mean_shifted.shape)  # Prints (2, 3)

(2, 3)
[2.  3.5 5. ]
(3,)

 [[-1.  -1.5 -2. ]
 [ 1.   1.5  2. ]]
(2, 3)


In [5]:
import numpy as np 

x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(.....) # Prints [[ 2  4  6]
             #         [ 6 10 14]]

[[ 2  4  6]
 [ 6 10 14]]


## LAB 문제
* x matrix의 각 요소 값들을 각 요소가 속한 행의 평균 값으로 빼려고 함 
* 다음 아래 코드의 오류를 해결하세요

In [6]:
import numpy as np

x = np.array([[1, 2, 3],
              [3, 5, 7]])

row_means = x.mean(axis=1)
print(row_means)  # Prints [2. 5.]
print(x.shape, row_means.shape)  # (2, 3) (2,)

mean_shifted = x - row_means  # error

[2. 5.]
(2, 3) (2,)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

## LAB 문제 - Compute outer product of vectors
* v = np.array([1, 2, 3])  # v has shape (3,)
* w = np.array([4, 5])    # w has shape (2,)
* To compute an outer product, we first reshape v to be a column vector of shape (3, 1); we can then broadcast it against w to yield an output of shape (3, 2), which is the outer product of v and w: [[ 4  5] [ 8 10] [12 15]]

## LAB 해결 - Compute outer product of vectors

In [8]:
import numpy as np

v = np.array([1, 2, 3])  # v has shape (3,)
w = np.array([4, 5])    # w has shape (2,)

# v * w  ???
.......

[[ 4  5]
 [ 8 10]
 [12 15]]


## Add a vector to each row of a matrix
* x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
* giving the following matrix: [[2 4 6] [5 7 9]]

In [10]:
x = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([1, 2, 3])  # v has shape (3,)
print(x + v)

[[2 4 6]
 [5 7 9]]


## LAB 문제 - Add a vector to each column of a matrix
* x has shape (2, 3) and w has shape (2,).
* If we transpose x then it has shape (3, 2) and can be broadcast
 against w to yield a result of shape (3, 2); transposing this result
 yields the final result of shape (2, 3) which is the matrix x with
 the vector w added to each column. Gives the following matrix: [[ 5  6  7] [ 9 10 11]]

* Another solution is to reshape w to be a column vector of shape (2, 1); we can then broadcast it directly against x to produce the same output.
* x = np.array([[1, 2, 3], [4, 5, 6]])
* w = np.array([4, 5])    # w has shape (2,)

## LAB 해결 - Add a vector to each column of a matrix

In [11]:
x = np.array([[1, 2, 3], [4, 5, 6]])
w = np.array([4, 5])    # w has shape (2,)

# method - 1
....
# method - 2 
....

[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
